name: ppob_koperasi_payment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.9.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  flutter_form_builder: ^10.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0

flutter_gen:
  integrations:
    image: true
    flutter_svg: true
    lottie: true


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800